Todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
]

todo/urls.py
from django.urls import path

from todo.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    toggle_complete_task,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "tasks/<int:pk>/update",
        TaskUpdateView.as_view(),
        name="task-update"),
    path(
        "tasks/<int:pk>/delete",
        TaskDeleteView.as_view(),
        name="task-delete"),
    path(
        "tasks/<int:pk>/toggle_complete_task/",
        toggle_complete_task,
        name="toggle_complete_task",
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create"
    ),
    path(
        "tags/<int:pk>/update",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/<int:pk>/delete",
        TagDeleteView.as_view(),
        name="tag-delete"
    ),
]

app_name = "todo"

todo/models.py
from django.db import models

# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    date_create = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=False, blank=True)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ("status", "-date_create")

    def __str__(self):
        return self.content

todo/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone

from todo.models import Task, Tag


class TaskForm(forms.ModelForm):
    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"})
    )
    tag = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    def clean(self):
        cleaned_data = super().clean()
        created_at = timezone.now()  # Use timezone-aware now
        deadline = cleaned_data.get("deadline")

        if deadline and deadline < created_at:
            raise ValidationError("Deadline can't be before the current time.")

        return cleaned_data

    class Meta:
        model = Task
        fields = (
            "content",
            "deadline",
            "tags",
        )

todo/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect

from todo.models import Task, Tag
from todo.forms import TaskForm


class TaskListView(generic.ListView):
    model = Task
    template_name = "todo/task_list.html"
    queryset = Task.objects.prefetch_related("tags")


class TaskCreateView(generic.CreateView):
    model = Task
    template_name = "todo/task_form.html"
    success_url = reverse_lazy("todo:task-list")
    form_class = TaskForm


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "todo/task_form.html"
    success_url = reverse_lazy("todo:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task-list")


def toggle_complete_task(request: HttpRequest, pk: int) -> HttpResponse:
    task = Task.objects.get(pk=pk)
    task.status = not task.status
    task.save()
    return HttpResponseRedirect(reverse_lazy("todo:task-list"))


class TagListView(generic.ListView):
    model = Tag
    context_object_name = "tags"
    success_url = reverse_lazy("todo:tag-list")
    template_name = "todo/tag_list.html"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")
    template_name = "todo/tag_form.html"


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo:tag-list")
    template_name = "todo/tag_form.html"


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}
    <title>TODO list</title>
  {% endblock %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body style="margin-top: 20px">
<div class="container-fluid">
<div class="row">
    <div class="col-sm-10">
      <ul>
        <li class="list-group-item"><a style="text-decoration: none" href="{% url "todo:task-list" %}">Home</a></li>
        <li class="list-group-item"><a style="text-decoration: none" href="{% url "todo:tag-list" %}">Tags</a></li>
      </ul>
      <div class="col-sm-9">
        {% block content %}
          
        {% endblock %}
      </div>
    </div>
  </div>
</div>

</body>
</html>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h2>Do you want to delete this tag: "{{ tag.name }}"?</h2>
  <form action="" method="post">
    {% csrf_token %}
    <a class="btn btn-secondary" href="{% url "todo:tag-list" %}">
      Cancel
    </a>
    <input class="btn btn-danger" type="submit" value="Yes">
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-success" type="submit" value="Submit">
    </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags:
    <a style="float: right" class="btn btn-primary" href="{% url "todo:tag-create" %}">
      Add
    </a>
  </h1>
  <table class="table">
  
    <tr>
      <th>Name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
    {% for tag in tags %}
      <tr>
        <td>{{ tag.name }}</td>
          <td>
            <form action="{% url 'todo:tag-update' pk=tag.id %}" method="get">
              <button type="submit" class="btn btn-primary">UPDATE</button>
            </form>
          </td>
          <td>
            <form action="{% url 'todo:tag-delete' pk=tag.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">DELETE</button>
            </form>
          </td>
      </tr>
    {% endfor %}
  </table>
  
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Do you want to delete this task: "{{ task }}"?</h1>
    <form action="" method="post">
      {% csrf_token %}
      <a class="btn btn-secondary" href="{% url "todo:task-list" %}">
        Cancel
      </a>
      <input class="btn btn-danger" type="submit" value="Yes">
    </form>
  </div>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
    <br>
      <input class="btn btn-success" type="submit" value="Submit">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Task List
    <a style="float: right" class="btn btn-primary" href="{% url "todo:task-create" %}">
      Add Task
    </a>
  </h1>
  <ul class="list-group list-group-flush">
    {% for task in task_list %}
      <li class="list-group-item">
        <h5>
          {{ task.content }}
          {% if task.done %}
            <span class="badge bg-success">Done</span>
            <a style="float:right;" class="btn btn-secondary" href="{% url "todo:toggle_complete_task" pk=task.id %}">Undo</a>
          {% else %}
            <span class="badge bg-danger">Not Done</span>
            <a style="float:right;" class="btn btn-success" href="{% url "todo:toggle_complete_task" pk=task.id %}">Complete</a>
          {% endif %}
        </h5>
        <p>
          Created: {{ task.date_create}} 
          {% if task.deadline and not task.status %}
           | Deadline: {{ task.deadline }}
          {% endif %}
        </p>
        <p>
          <strong>
            Tags:
          </strong>
          {% for tag in task.tags.all %}
            {{ tag.name }}
          {% endfor %}
        </p>
        <p>
          <a style="text-decoration: none" href="{% url "todo:task-update" pk=task.id %}">Update</a>
          <a style="text-decoration: none" href="{% url "todo:task-delete" pk=task.id %}">Delete</a>
        </p>
      </li>
    {% endfor %}
  </ul>
{% endblock %}